---
- name: Create aws webserver instances
  hosts: localhost
  module_defaults:
    group/aws:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'

  tasks:
  - name: Create firewall rule to allow http traffic
    amazon.aws.ec2_instance:
      name: default
      fwname: "my-http-fw-rule"
      allowed: tcp:80
      state: present
      src_range: "0.0.0.0/0"
      target_tags: "http-server"

  - name: Create instances based on image {{ image }}
    amazon.aws.ec2_instance:
      key_name: "example-ssh-key"
      image_id: "..."
    register: aws

  - name: Save hosts data within a group
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: aws_instances_temp
    with_items: "{{ aws.instance_data }}"

  - name: Wait for ssh to come up
    wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
    with_items: "{{ aws.instance_data }}"

  - name: Setting ip as instance fact
    set_fact: host={{ item.public_ip }}
    with_items: "{{ aws.instance_data }}"

- name: Configure instance post-creation
  hosts: aws_instances_temp
  gather_facts: True
  remote_user: \\*Your aws user*\\
  become: yes
  become_method: sudo

  roles:

    - \\*path_to_role*\\/myapache
