---
- name: Playbook to create aws load balancing instance
  hosts: localhost
  module_defaults:
    group/aws:
      aws_access_key: '{{ aws_access_key }}'
      aws_secret_key: '{{ aws_secret_key }}'
      region: '{{ region }}'

  tasks:
    - name: Create aws load balancer
      amazon.aws.ec2_instance:
        key_name: "example-ssh-key"
        name: lbserver
        state: present
        region: us-central1
        members: ['us-central1-a/web1','us-central1-a/web2','us-central1-a/web3']
        httphealthcheck_name: hc
        httphealthcheck_port: 80
        httphealthcheck_path: "/"

